In [2]:
import random
import numpy as np

## U_iの生成

In [3]:
import random

In [4]:
import numpy as np

In [5]:
p_1=50
r_J=10
p_2=50
n=50



In [6]:
U_1=np.random.uniform(low=0.5, high=1, size=(p_1,r_J))
U_2=np.random.uniform(low=0.5, high=1, size=(p_2,r_J))

## theta_1の生成

In [7]:
r_prop=0.8

In [8]:


vec_theta_1_a=np.random.uniform(low=0.5, high=1, size=int(r_J*r_prop))
vec_theta_1_b=np.zeros(int(r_J-r_J*r_prop))

vec_theta_1=np.concatenate((vec_theta_1_a,vec_theta_1_b))
vec_theta_1=vec_theta_1.reshape(1,r_J)


In [9]:
vec_theta_1.shape

(1, 10)

In [10]:
U_1.shape

(50, 10)

## U_iとtheta_1の更新

In [11]:
U_theta_1=np.row_stack((U_1,U_2,vec_theta_1))
U_theta_1

array([[0.83847253, 0.55966128, 0.94440054, ..., 0.51159436, 0.80077311,
        0.68948406],
       [0.6992576 , 0.50441676, 0.65847732, ..., 0.85695963, 0.72265791,
        0.62802013],
       [0.89778028, 0.80607992, 0.71502184, ..., 0.5245767 , 0.50246795,
        0.97237853],
       ...,
       [0.71518612, 0.93008447, 0.74735881, ..., 0.8630661 , 0.67842177,
        0.74530115],
       [0.95228693, 0.59834677, 0.92739577, ..., 0.90327396, 0.62407172,
        0.61766064],
       [0.72176034, 0.97553363, 0.92758369, ..., 0.515768  , 0.        ,
        0.        ]])

In [12]:
U_theta_1.shape


(101, 10)

In [13]:
U_theta_1_Q,R=np.linalg.qr(U_theta_1)
U_theta_1_Q.shape

(101, 10)

In [14]:
U_1_new=U_theta_1_Q[:p_1,:]
U_2_new=U_theta_1_Q[p_1:p_1+p_2,:]
theta_1_new=U_theta_1_Q[p_1+p_2:,:]

In [16]:
np.dot(U_theta_1_Q.T,U_theta_1_Q)

array([[ 1.00000000e+00,  1.17809811e-17, -5.22261360e-17,
        -8.40811174e-18,  1.27574419e-17, -1.18636908e-17,
         1.67683994e-18, -2.87076422e-17, -9.30733153e-19,
         2.39626090e-18],
       [ 1.17809811e-17,  1.00000000e+00, -2.93059670e-17,
        -2.32430586e-17,  2.68912392e-17,  5.69654056e-17,
        -2.32705259e-17,  5.85638516e-17, -2.26094425e-17,
        -2.16458796e-17],
       [-5.22261360e-17, -2.93059670e-17,  1.00000000e+00,
         4.08304636e-17,  7.14145853e-17,  2.79950582e-17,
        -1.22192428e-16,  9.61260694e-17,  1.31324998e-16,
        -1.21675435e-16],
       [-8.40811174e-18, -2.32430586e-17,  4.08304636e-17,
         1.00000000e+00, -6.53632165e-17, -4.14689103e-17,
         1.19558252e-17, -2.40981285e-17, -7.90229375e-17,
         1.08657782e-17],
       [ 1.27574419e-17,  2.68912392e-17,  7.14145853e-17,
        -6.53632165e-17,  1.00000000e+00,  7.50456089e-17,
         2.07975740e-17,  1.75555783e-17,  1.45479412e-17,
         1.

## S_Jの作成

In [17]:
w_J=2.0

In [18]:
diag_joint_matrix = np.diag([w_J] * r_J)
diag_joint_matrix

array([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]])

In [19]:
S_J_old=np.random.uniform(low=0, high=1, size=(r_J,n))
S_J_old.shape

(10, 50)

In [20]:
S_J=np.dot(diag_joint_matrix,S_J_old)
S_J.shape

(10, 50)

## W_iの生成

In [21]:
r_1=5
r_2=5


In [22]:
W_1=np.random.uniform(low=0.5, high=1, size=(p_1,r_1))
W_2=np.random.uniform(low=0.5, high=1, size=(p_2,r_2))

## theta_{2i}の生成

In [23]:
vec_theta_21_a=np.random.uniform(low=0.5, high=1, size=int(r_1*r_prop))
vec_theta_21_b=np.zeros(int(r_1-r_1*r_prop))
vec_theta_21=np.concatenate((vec_theta_21_a,vec_theta_21_b))
vec_theta_21=vec_theta_21.reshape(1,r_1)
vec_theta_21

array([[0.70023121, 0.64957509, 0.9164587 , 0.57063079, 0.        ]])

In [24]:
vec_theta_22_a=np.random.uniform(low=0.5, high=1, size=int(r_2*r_prop))
vec_theta_22_b=np.zeros(int(r_2-r_2*r_prop))
vec_theta_22=np.concatenate((vec_theta_22_a,vec_theta_22_b))
vec_theta_22=vec_theta_22.reshape(1,r_2)
vec_theta_22

array([[0.51630821, 0.99364451, 0.95212841, 0.51758854, 0.        ]])

## W_1とtheta_{21}の更新

In [25]:
W_theta_21=np.row_stack((W_1,vec_theta_21))
W_theta_21.shape

(51, 5)

In [26]:
W_theta_21_Q,R=np.linalg.qr(W_theta_21)
W_theta_21_Q.shape

(51, 5)

In [27]:
W_theta_22=np.row_stack((W_2,vec_theta_22))
W_theta_22.shape

(51, 5)

In [28]:
W_theta_22_Q,R=np.linalg.qr(W_theta_22)
W_theta_22_Q.shape

(51, 5)

In [29]:
W_1_new=W_theta_21_Q[:p_1,:]
W_2_new=W_theta_22_Q[:p_2,:]
theta_21_new=W_theta_21_Q[p_1:,:]
theta_22_new=W_theta_22_Q[p_2:,:]

## S_iの生成

In [30]:
w_1=1.0
w_2=2.0

In [31]:
diag_x1_matrix = np.diag([w_1] * r_1)
diag_x1_matrix.shape

(5, 5)

In [32]:
S_1_old=np.random.uniform(low=0, high=1, size=(r_1,n))
S_1_old.shape

(5, 50)

In [33]:
P_SJ=S_J.T.dot(np.linalg.inv(S_J.dot(S_J.T))).dot(S_J)
P_SJ.shape

(50, 50)

In [34]:
diag_matrix = np.diag([1] * n)
P_SJ_C=diag_matrix-P_SJ
P_SJ_C.shape

(50, 50)

In [35]:
S_1=diag_x1_matrix.dot(S_1_old).dot(P_SJ_C)
S_1.shape

(5, 50)

In [36]:
diag_x2_matrix = np.diag([w_2] * r_2)
S_2_old=np.random.uniform(low=0, high=1, size=(r_2,n))
S_2=diag_x2_matrix.dot(S_2_old).dot(P_SJ_C)
S_2.shape

(5, 50)

## X_iの生成

In [37]:
X1_erro=0.2
X2_erro=0.2
y_erro=0.2

In [38]:
X_1=U_1_new.dot(S_J)+W_1_new.dot(S_1)
var_X1=np.var(X_1)
var_X1

0.11663941841399719

In [39]:
var_E1=X1_erro*var_X1
var_E1

0.02332788368279944

In [40]:
E_1=np.random.normal(loc=0, scale=np.sqrt(var_E1), size=(p_1,n))
X_1=X_1+E_1

In [41]:
X_2=U_2_new.dot(S_J)+W_2_new.dot(S_2)
var_X2=np.var(X_2)
var_E2=X2_erro*var_X2
E_2=np.random.normal(loc=0, scale=np.sqrt(var_E2), size=(p_2,n))
X_2=X_2+E_2

## yの生成


In [42]:
y=theta_1_new.dot(S_J)+theta_21_new.dot(S_1)+theta_22_new.dot(S_2)
var_y=np.var(y)
var_e_y=y_erro*var_y
e_y=np.random.normal(loc=0, scale=np.sqrt(var_e_y), size=(1,n))
y=y+e_y


In [43]:
y

array([[ 1.10262309,  0.96815155,  0.06388595,  0.14761586,  0.79780479,
         0.99800179,  1.18874895,  0.75483307,  0.36623859,  1.59452765,
        -0.58017706,  1.94824755,  0.87449209,  1.21963427,  1.21531879,
         0.33254952,  1.36971826,  1.59907205,  1.49158811,  0.45729938,
         1.44419586,  0.97628136,  0.75711719,  1.16300141,  1.26956521,
         0.26660778,  0.52011215,  0.90029359,  0.72528898,  0.62305636,
        -0.12160178,  1.50911277,  0.78114143,  1.82338089,  1.26738331,
         0.60475489,  0.75970077,  1.47211585,  1.18534191,  2.12386307,
         0.38286511,  0.67813254, -0.44719636, -0.2976923 ,  0.45173736,
         0.50268463,  0.80216821,  1.48217313,  0.96909713,  0.29362188]])

In [44]:
y.shape

(1, 50)

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
ms = StandardScaler()
X_1_final = ms.fit_transform(X_1)

In [56]:
y_final=(y-np.mean(y))/np.std(y)
np.var(y_final)

0.9999999999999997

In [49]:
np.var(y)

0.348594944904288

In [139]:
import function

In [141]:
X_1,X_2,y=function.gene_data(p_1=50,p_2=50,n=100,r_J=10,r_1=5,r_2=5,r_prop=0.8,w_J=2.0,w_1=1.0,w_2=1.0,X1_erro=0.2,X2_erro=0.2,y_erro=0.2)


In [142]:
np.var(X_1)

1.0

In [140]:
np.var(X_1)

0.1307661393663321

In [ ]:
norm_v = np.linalg.norm(v)