In [46]:
import random
import numpy as np

U_iの生成

In [8]:
import random
import numpy as np

p_i=100
r_J=5

vec_u_i= []
for i in range(p_i*r_J):
    x = random.uniform(0.5, 1)  # 0.5から1までの範囲で一様分布に従う乱数を生成する
    vec_u_i.append(x)
print(vec_u_i)
len(vec_u_i)

[0.9912223517561479, 0.6413636984821653, 0.5304645597152804, 0.6402516279299282, 0.8037952344008263, 0.5971398392515042, 0.7238899738816582, 0.8721986873458629, 0.9315764279629418, 0.6158857689047808, 0.7402121253271641, 0.731367820729339, 0.5564560538701813, 0.846414284910049, 0.6171081038086901, 0.7018593040336581, 0.5694038400677763, 0.6702416766192943, 0.6751833843239099, 0.7207643449427678, 0.8741050209995348, 0.9007063129180617, 0.8944769478159064, 0.5408559974920645, 0.8388836990340891, 0.6969796792432732, 0.9839867545895995, 0.6194245708890305, 0.9921181398955596, 0.8859721645141225, 0.7901335781651407, 0.6600328262657593, 0.7195655560874834, 0.5462050359171189, 0.6246362749866512, 0.9463987200766559, 0.9626524585211523, 0.8324788570216136, 0.7431426737333398, 0.9485487352063118, 0.7995777486350268, 0.6005973680211297, 0.813642059273902, 0.6922059849001145, 0.5109386998641019, 0.8514595652357538, 0.6162334277037326, 0.7056201903732366, 0.8817552475721422, 0.8838761713229726, 0.

500

In [9]:
U_i=np.array(vec_u_i).reshape(p_i,r_J)
U_i

array([[0.99122235, 0.6413637 , 0.53046456, 0.64025163, 0.80379523],
       [0.59713984, 0.72388997, 0.87219869, 0.93157643, 0.61588577],
       [0.74021213, 0.73136782, 0.55645605, 0.84641428, 0.6171081 ],
       [0.7018593 , 0.56940384, 0.67024168, 0.67518338, 0.72076434],
       [0.87410502, 0.90070631, 0.89447695, 0.540856  , 0.8388837 ],
       [0.69697968, 0.98398675, 0.61942457, 0.99211814, 0.88597216],
       [0.79013358, 0.66003283, 0.71956556, 0.54620504, 0.62463627],
       [0.94639872, 0.96265246, 0.83247886, 0.74314267, 0.94854874],
       [0.79957775, 0.60059737, 0.81364206, 0.69220598, 0.5109387 ],
       [0.85145957, 0.61623343, 0.70562019, 0.88175525, 0.88387617],
       [0.86046645, 0.58789991, 0.98882816, 0.98648771, 0.55461444],
       [0.91412571, 0.93441267, 0.54794806, 0.6591917 , 0.99092074],
       [0.77993787, 0.83844573, 0.90486443, 0.80157284, 0.94667092],
       [0.67502316, 0.97899373, 0.79280768, 0.84501241, 0.69966988],
       [0.77756581, 0.77042033, 0.

In [53]:
from function import *

In [54]:
import random

In [55]:

U_i=gene_u_i(p_i=100,r_J=5)
U_i

NameError: name 'random' is not defined

theta_1の生成

In [28]:
r_J=10
r_prop=0.8

vec_theta_1_a=[]
for i in range(int(r_J*r_prop)):
    x=random.uniform(0.5, 1)
    vec_theta_1_a.append(x)
print(vec_theta_1_a)
len(vec_theta_1_a)
    


[0.9989489712179696, 0.7795213052661065, 0.7624734670799165, 0.7586510246017744, 0.733769173164144, 0.8782550112636882, 0.5840664192876537, 0.6398613588812014]


8

In [16]:
vec_theta_1_b=np.zeros(int(r_J-r_J*r_prop))
vec_theta_1_b

array([0., 0.])

In [17]:
vec_theta_1=np.concatenate((vec_theta_1_a,vec_theta_1_b))
vec_theta_1

array([0.7724407 , 0.59806633, 0.72386801, 0.71999518, 0.63165644,
       0.67154455, 0.74424282, 0.83136233, 0.        , 0.        ])