In [47]:
import random
import numpy as np

## U_iの生成

In [48]:
import random

In [49]:
import numpy as np

In [50]:
p_1=50
r_J=10
p_2=50
n=50



In [54]:
U_1=np.random.uniform(low=0.5, high=1, size=(p_1,r_J))
U_2=np.random.uniform(low=0.5, high=1, size=(p_2,r_J))

## theta_1の生成

In [53]:
r_prop=0.8

In [7]:


vec_theta_1_a=np.random.uniform(low=0.5, high=1, size=int(r_J*r_prop))
vec_theta_1_b=np.zeros(int(r_J-r_J*r_prop))

vec_theta_1=np.concatenate((vec_theta_1_a,vec_theta_1_b))
vec_theta_1=vec_theta_1.reshape(1,r_J)


In [55]:
vec_theta_1.shape

(1, 10)

In [56]:
U_1.shape

(50, 10)

## U_iとtheta_1の更新

In [57]:
U_theta_1=np.row_stack((U_1,U_2,vec_theta_1))
U_theta_1

array([[0.8057086 , 0.98126692, 0.95901061, ..., 0.5872768 , 0.94283733,
        0.92872267],
       [0.771639  , 0.93826428, 0.76521329, ..., 0.77692243, 0.59361478,
        0.90614085],
       [0.92998439, 0.78458491, 0.64857214, ..., 0.924177  , 0.90650096,
        0.50362757],
       ...,
       [0.96837606, 0.60290049, 0.923807  , ..., 0.69973248, 0.64669162,
        0.50785993],
       [0.73398198, 0.7554376 , 0.95296363, ..., 0.83319243, 0.59219516,
        0.80110532],
       [0.64231123, 0.97237385, 0.94201473, ..., 0.94650772, 0.        ,
        0.        ]])

In [58]:
U_theta_1.shape


(101, 10)

In [59]:
U_theta_1_Q,R=np.linalg.qr(U_theta_1)
U_theta_1_Q.shape

(101, 10)

In [60]:
U_1_new=U_theta_1_Q[:p_1,:]
U_2_new=U_theta_1_Q[p_1:p_1+p_2,:]
theta_1_new=U_theta_1_Q[p_1+p_2:,:]

In [61]:
np.dot(U_theta_1_Q.T,U_theta_1_Q)

array([[ 1.00000000e+00, -5.56689477e-17,  1.41901461e-17,
         1.00980656e-16, -2.72648526e-17,  7.68850734e-18,
         3.77226224e-17,  5.28447292e-17, -6.52003381e-17,
         8.10851373e-17],
       [-5.56689477e-17,  1.00000000e+00, -3.40586558e-18,
         5.05496804e-18,  2.27377760e-17, -2.35542080e-17,
         1.36265291e-17,  1.38635549e-17,  6.46127536e-17,
        -2.60598339e-17],
       [ 1.41901461e-17, -3.40586558e-18,  1.00000000e+00,
         5.84171441e-17, -9.55053832e-18,  1.09107680e-17,
         3.43258570e-17,  2.12079641e-17,  5.64556842e-17,
         3.89850736e-17],
       [ 1.00980656e-16,  5.05496804e-18,  5.84171441e-17,
         1.00000000e+00, -1.00478766e-16, -3.98462190e-17,
        -8.79538362e-18, -5.47914430e-17, -5.05202260e-17,
        -1.06215048e-17],
       [-2.72648526e-17,  2.27377760e-17, -9.55053832e-18,
        -1.00478766e-16,  1.00000000e+00,  1.43161432e-17,
        -3.13948749e-18, -1.68669892e-17, -4.36168664e-17,
         1.

## S_Jの作成

In [62]:
w_J=2.0

In [63]:
diag_joint_matrix = np.diag([w_J] * r_J)
diag_joint_matrix

array([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]])

In [64]:
S_J_old=np.random.uniform(low=0, high=1, size=(r_J,n))
S_J_old.shape

(10, 50)

In [65]:
S_J=np.dot(diag_joint_matrix,S_J_old)
S_J.shape

(10, 50)

## W_iの生成

In [66]:
r_1=5
r_2=5


In [67]:
W_1=np.random.uniform(low=0.5, high=1, size=(p_1,r_1))
W_2=np.random.uniform(low=0.5, high=1, size=(p_2,r_2))

## theta_{2i}の生成

In [68]:
vec_theta_21_a=np.random.uniform(low=0.5, high=1, size=int(r_1*r_prop))
vec_theta_21_b=np.zeros(int(r_1-r_1*r_prop))
vec_theta_21=np.concatenate((vec_theta_21_a,vec_theta_21_b))
vec_theta_21=vec_theta_21.reshape(1,r_1)
vec_theta_21

array([[0.85065727, 0.79906217, 0.57419818, 0.76932887, 0.        ]])

In [69]:
vec_theta_22_a=np.random.uniform(low=0.5, high=1, size=int(r_2*r_prop))
vec_theta_22_b=np.zeros(int(r_2-r_2*r_prop))
vec_theta_22=np.concatenate((vec_theta_22_a,vec_theta_22_b))
vec_theta_22=vec_theta_22.reshape(1,r_2)
vec_theta_22

array([[0.53343435, 0.62070434, 0.5015465 , 0.8723312 , 0.        ]])

## W_1とtheta_{21}の更新

In [70]:
W_theta_21=np.row_stack((W_1,vec_theta_21))
W_theta_21.shape

(51, 5)

In [71]:
W_theta_21_Q,R=np.linalg.qr(W_theta_21)
W_theta_21_Q.shape

(51, 5)

In [72]:
W_theta_22=np.row_stack((W_2,vec_theta_22))
W_theta_22.shape

(51, 5)

In [73]:
W_theta_22_Q,R=np.linalg.qr(W_theta_22)
W_theta_22_Q.shape

(51, 5)

In [74]:
W_1_new=W_theta_21_Q[:p_1,:]
W_2_new=W_theta_22_Q[:p_2,:]
theta_21_new=W_theta_21_Q[p_1:,:]
theta_22_new=W_theta_22_Q[p_2:,:]

## S_iの生成

In [75]:
w_1=1.0
w_2=2.0

In [76]:
diag_x1_matrix = np.diag([w_1] * r_1)
diag_x1_matrix.shape

(5, 5)

In [77]:
S_1_old=np.random.uniform(low=0, high=1, size=(r_1,n))
S_1_old.shape

(5, 50)

In [78]:
P_SJ=S_J.T.dot(np.linalg.inv(S_J.dot(S_J.T))).dot(S_J)
P_SJ.shape

(50, 50)

In [79]:
diag_matrix = np.diag([1] * n)
P_SJ_C=diag_matrix-P_SJ
P_SJ_C.shape

(50, 50)

In [80]:
S_1=diag_x1_matrix.dot(S_1_old).dot(P_SJ_C)
S_1.shape

(5, 50)

In [81]:
diag_x2_matrix = np.diag([w_2] * r_2)
S_2_old=np.random.uniform(low=0, high=1, size=(r_2,n))
S_2=diag_x2_matrix.dot(S_2_old).dot(P_SJ_C)
S_2.shape

(5, 50)

## X_iの生成

In [82]:
X1_erro=0.2
X2_erro=0.2
y_erro=0.2

In [83]:
X_1=U_1_new.dot(S_J)+W_1_new.dot(S_1)
var_X1=np.var(X_1)
var_X1

0.1326059255585994

In [84]:
var_E1=X1_erro*var_X1
var_E1

0.026521185111719883

In [85]:
E_1=np.random.normal(loc=0, scale=np.sqrt(var_E1), size=(p_1,n))
X_1=X_1+E_1

In [86]:
X_2=U_2_new.dot(S_J)+W_2_new.dot(S_2)
var_X2=np.var(X_2)
var_E2=X2_erro*var_X2
E_2=np.random.normal(loc=0, scale=np.sqrt(var_E2), size=(p_2,n))
X_2=X_2+E_2

## yの生成


In [87]:
y=theta_1_new.dot(S_J)+theta_21_new.dot(S_1)+theta_22_new.dot(S_2)
var_y=np.var(y)
var_e_y=y_erro*var_y
e_y=np.random.normal(loc=0, scale=np.sqrt(var_e_y), size=(1,n))
y=y+e_y


In [88]:
y.shape

(1, 50)

In [89]:
from sklearn.preprocessing import StandardScaler

In [91]:
ms = StandardScaler()
X_1_final = ms.fit_transform(X_1)

In [94]:
np.var(X_1_final)

1.0