In [47]:
import random
import numpy as np

## U_iの生成

In [48]:
import random

In [49]:
import numpy as np

In [98]:
p_1=50
r_J=10
p_2=50
n=50



In [99]:
U_1=np.random.uniform(low=0.5, high=1, size=(p_1,r_J))
U_2=np.random.uniform(low=0.5, high=1, size=(p_2,r_J))

## theta_1の生成

In [100]:
r_prop=0.8

In [101]:


vec_theta_1_a=np.random.uniform(low=0.5, high=1, size=int(r_J*r_prop))
vec_theta_1_b=np.zeros(int(r_J-r_J*r_prop))

vec_theta_1=np.concatenate((vec_theta_1_a,vec_theta_1_b))
vec_theta_1=vec_theta_1.reshape(1,r_J)


In [103]:
vec_theta_1.shape

(1, 10)

In [104]:
U_1.shape

(50, 10)

## U_iとtheta_1の更新

In [105]:
U_theta_1=np.row_stack((U_1,U_2,vec_theta_1))
U_theta_1

array([[0.60729016, 0.88038845, 0.82745043, ..., 0.6971093 , 0.98318935,
        0.78155107],
       [0.61976722, 0.55290677, 0.92567519, ..., 0.82060181, 0.79988463,
        0.65682938],
       [0.77945717, 0.87663628, 0.89290543, ..., 0.85060581, 0.54688014,
        0.91697928],
       ...,
       [0.53522705, 0.79785532, 0.66721516, ..., 0.7658806 , 0.56939373,
        0.66586039],
       [0.55032307, 0.9505526 , 0.57745401, ..., 0.69647844, 0.64302602,
        0.52200273],
       [0.68666004, 0.57845769, 0.52230307, ..., 0.86855449, 0.        ,
        0.        ]])

In [106]:
U_theta_1.shape


(101, 10)

In [107]:
U_theta_1_Q,R=np.linalg.qr(U_theta_1)
U_theta_1_Q.shape

(101, 10)

In [108]:
U_1_new=U_theta_1_Q[:p_1,:]
U_2_new=U_theta_1_Q[p_1:p_1+p_2,:]
theta_1_new=U_theta_1_Q[p_1+p_2:,:]

In [109]:
np.dot(U_theta_1_Q.T,U_theta_1_Q)

array([[ 1.00000000e+00,  5.69003295e-17,  1.88911492e-19,
         5.63455086e-17,  3.95313588e-17, -4.69793158e-17,
        -1.60483792e-17,  4.50828127e-17,  1.03044682e-18,
        -2.62191298e-17],
       [ 5.69003295e-17,  1.00000000e+00, -1.45480663e-16,
         7.33337461e-17,  3.70219013e-17, -6.05214822e-18,
        -8.82752175e-17,  1.76922244e-17, -7.31723344e-18,
         4.46328758e-17],
       [ 1.88911492e-19, -1.45480663e-16,  1.00000000e+00,
         3.99674077e-17,  2.86649095e-17,  1.04742001e-17,
        -2.67590299e-17,  1.27875127e-17, -1.21926942e-17,
         5.77023823e-18],
       [ 5.63455086e-17,  7.33337461e-17,  3.99674077e-17,
         1.00000000e+00,  4.15029687e-17, -5.38832910e-18,
         7.33161156e-18, -5.25136912e-17,  8.08457984e-17,
        -1.15405739e-18],
       [ 3.95313588e-17,  3.70219013e-17,  2.86649095e-17,
         4.15029687e-17,  1.00000000e+00, -2.65326324e-17,
         3.52933507e-18,  2.78451338e-17,  1.22449025e-16,
        -1.

## S_Jの作成

In [110]:
w_J=2.0

In [111]:
diag_joint_matrix = np.diag([w_J] * r_J)
diag_joint_matrix

array([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]])

In [112]:
S_J_old=np.random.uniform(low=0, high=1, size=(r_J,n))
S_J_old.shape

(10, 50)

In [113]:
S_J=np.dot(diag_joint_matrix,S_J_old)
S_J.shape

(10, 50)

## W_iの生成

In [114]:
r_1=5
r_2=5


In [115]:
W_1=np.random.uniform(low=0.5, high=1, size=(p_1,r_1))
W_2=np.random.uniform(low=0.5, high=1, size=(p_2,r_2))

## theta_{2i}の生成

In [116]:
vec_theta_21_a=np.random.uniform(low=0.5, high=1, size=int(r_1*r_prop))
vec_theta_21_b=np.zeros(int(r_1-r_1*r_prop))
vec_theta_21=np.concatenate((vec_theta_21_a,vec_theta_21_b))
vec_theta_21=vec_theta_21.reshape(1,r_1)
vec_theta_21

array([[0.53082142, 0.76930636, 0.79582265, 0.88439866, 0.        ]])

In [117]:
vec_theta_22_a=np.random.uniform(low=0.5, high=1, size=int(r_2*r_prop))
vec_theta_22_b=np.zeros(int(r_2-r_2*r_prop))
vec_theta_22=np.concatenate((vec_theta_22_a,vec_theta_22_b))
vec_theta_22=vec_theta_22.reshape(1,r_2)
vec_theta_22

array([[0.84560067, 0.60524039, 0.630047  , 0.54326018, 0.        ]])

## W_1とtheta_{21}の更新

In [118]:
W_theta_21=np.row_stack((W_1,vec_theta_21))
W_theta_21.shape

(51, 5)

In [71]:
W_theta_21_Q,R=np.linalg.qr(W_theta_21)
W_theta_21_Q.shape

(51, 5)

In [119]:
W_theta_22=np.row_stack((W_2,vec_theta_22))
W_theta_22.shape

(51, 5)

In [120]:
W_theta_22_Q,R=np.linalg.qr(W_theta_22)
W_theta_22_Q.shape

(51, 5)

In [121]:
W_1_new=W_theta_21_Q[:p_1,:]
W_2_new=W_theta_22_Q[:p_2,:]
theta_21_new=W_theta_21_Q[p_1:,:]
theta_22_new=W_theta_22_Q[p_2:,:]

## S_iの生成

In [122]:
w_1=1.0
w_2=2.0

In [123]:
diag_x1_matrix = np.diag([w_1] * r_1)
diag_x1_matrix.shape

(5, 5)

In [124]:
S_1_old=np.random.uniform(low=0, high=1, size=(r_1,n))
S_1_old.shape

(5, 50)

In [125]:
P_SJ=S_J.T.dot(np.linalg.inv(S_J.dot(S_J.T))).dot(S_J)
P_SJ.shape

(50, 50)

In [126]:
diag_matrix = np.diag([1] * n)
P_SJ_C=diag_matrix-P_SJ
P_SJ_C.shape

(50, 50)

In [127]:
S_1=diag_x1_matrix.dot(S_1_old).dot(P_SJ_C)
S_1.shape

(5, 50)

In [128]:
diag_x2_matrix = np.diag([w_2] * r_2)
S_2_old=np.random.uniform(low=0, high=1, size=(r_2,n))
S_2=diag_x2_matrix.dot(S_2_old).dot(P_SJ_C)
S_2.shape

(5, 50)

## X_iの生成

In [129]:
X1_erro=0.2
X2_erro=0.2
y_erro=0.2

In [130]:
X_1=U_1_new.dot(S_J)+W_1_new.dot(S_1)
var_X1=np.var(X_1)
var_X1

0.10737290068304937

In [131]:
var_E1=X1_erro*var_X1
var_E1

0.021474580136609876

In [132]:
E_1=np.random.normal(loc=0, scale=np.sqrt(var_E1), size=(p_1,n))
X_1=X_1+E_1

In [133]:
X_2=U_2_new.dot(S_J)+W_2_new.dot(S_2)
var_X2=np.var(X_2)
var_E2=X2_erro*var_X2
E_2=np.random.normal(loc=0, scale=np.sqrt(var_E2), size=(p_2,n))
X_2=X_2+E_2

## yの生成


In [134]:
y=theta_1_new.dot(S_J)+theta_21_new.dot(S_1)+theta_22_new.dot(S_2)
var_y=np.var(y)
var_e_y=y_erro*var_y
e_y=np.random.normal(loc=0, scale=np.sqrt(var_e_y), size=(1,n))
y=y+e_y


In [135]:
y.shape

(1, 50)

In [136]:
from sklearn.preprocessing import StandardScaler

In [137]:
ms = StandardScaler()
X_1_final = ms.fit_transform(X_1)

In [138]:
np.var(X_1_final)

1.0

In [139]:
import function

In [141]:
X_1,X_2,y=function.gene_data(p_1=50,p_2=50,n=100,r_J=10,r_1=5,r_2=5,r_prop=0.8,w_J=2.0,w_1=1.0,w_2=1.0,X1_erro=0.2,X2_erro=0.2,y_erro=0.2)


In [142]:
np.var(X_1)

1.0

In [140]:
np.var(X_1)

0.1307661393663321

In [ ]:
norm_v = np.linalg.norm(v)